repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff-check
        # These rules are kept as warnings in an IDE and discouraged, but will not fail pre-commit
        # Rules that are fully ignored are in pyproject.toml
        args: ["--fix", "--ignore=PTH,C901,PLR0911,PLR0912,PLR0913,PLR0915,PLW0603,BLE001,TRY400,PERF203,FIX002,FBT001,FBT002"]
      - id: ruff-format
